import type { OrderDetailsResponse, CreateOrderResponse } from "../types/order.types";

export const orderDetailsResponseFixture: OrderDetailsResponse = [
  {
    address: "32424dsada43das4",
    balance_based: "false",
    confirmed_amount: 100,
    created_at: "2019-08-24T14:15:22Z",
    crypto_amount: 21,
    currency_id: "XRP",
    edited_at: "2019-08-24T14:38:22Z",
    expired_time: "2019-08-24T14:55:22Z",
    fiat: "EUR",
    fiat_amount: 100,
    good_fee: false,
    identifier: "3223asd-asdas213ads-234d",
    internal_data: null,
    language: "es",
    merchant_device_id: 1,
    notes: "test note",
    percentage: 0,
    rbf: false,
    received_amount: 0,
    reference: null,
    safe: false,
    status: "NR",
    tag_memo: "213213213",
    transactions: [],
    unconfirmed_amount: 0,
    url_ko: "",
    url_ok: "",
    url_standby: "",
  },
];

export const createOrderResponseFixture: CreateOrderResponse = {
  identifier: "8237823asdasd-2asd234-asd23234",
  reference: "test",
  payment_uri: "",
  web_url: "http://example.com",
  address: "xasd234ksdjjk34oms",
  tag_memo: "324234324",
  input_currency: "XRP",
  expected_input_amount: 10,
  rate: 0,
  notes: "test note",
  fiat: "EUR",
  language: "ES",
};
